import { randomUUID } from "node:crypto";
import { McpServer } from "@modelcontextprotocol/server";
import { serveStdio } from "@modelcontextprotocol/server/stdio";
import * as z from "zod/v4";

const baseUrl = String(process.env.MEMORY_HUB_URL || "http://127.0.0.1:8787").replace(/\/$/, "");
const token = String(process.env.MEMORY_HUB_TOKEN || "");

async function hub(pathname, { method = "GET", body } = {}) {
  const response = await fetch(baseUrl + pathname, { method, headers: { Accept: "application/json", ...(body === undefined ? {} : { "Content-Type": "application/json" }), ...(token ? { "X-Memory-Hub-Token": token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  const result = await response.json().catch(() => ({ ok: false, error: `HTTP ${response.status}` }));
  if (!response.ok) throw new Error(`${result.code || "HUB_ERROR"}: ${result.error || `HTTP ${response.status}`}`);
  return result;
}

const output = (value) => ({ content: [{ type: "text", text: JSON.stringify(value, null, 2) }], structuredContent: value });
const command = (type, characterId, payload, commandId = randomUUID()) => ({ commandId, type, actorId: "claude-code", characterId, worldId: null, issuedAt: new Date().toISOString(), protocolVersion: "1.0", payload });

function createServer() {
  const server = new McpServer({ name: "sully-memory-hub", version: "0.1.0" });
  server.registerTool("sully_get_character_context", { description: "Get the full stable character context when changed plus incremental chat, events, recall, runtime state and unfinished tasks. Optionally claim the next queued wake.", inputSchema: z.object({ characterId: z.string().min(1), reason: z.string().optional(), sessionId: z.string().optional(), claimNextWake: z.boolean().default(false), forceStable: z.boolean().default(false), recallLimit: z.number().int().min(1).max(5).default(5) }) }, async (args) => output(args.claimNextWake ? await hub("/api/v1/cc/wakes/claim", { method: "POST", body: args }) : await hub("/api/v1/cc/context", { method: "POST", body: args })));
  server.registerTool("sully_get_recent_messages", { description: "Read recent raw Hub messages without downloading the full history.", inputSchema: z.object({ characterId: z.string().min(1), after: z.number().int().min(0).default(0), limit: z.number().int().min(1).max(500).default(100), surface: z.enum(["chat", "activity", "world", "state", "memory", "schedule", "system"]).optional(), visibility: z.enum(["user", "internal"]).optional() }) }, async ({ characterId, after, limit, surface, visibility }) => { const q = new URLSearchParams({ charId: characterId, after: String(after), limit: String(limit) }); if (surface) q.set("surface", surface); if (visibility) q.set("visibility", visibility); return output(await hub(`/api/runtime/messages?${q}`)); });
  server.registerTool("sully_recall", { description: "Run Hub Memory Palace recall; use only when the automatic wake recall is insufficient.", inputSchema: z.object({ characterId: z.string().min(1), query: z.string().min(1), limit: z.number().int().min(1).max(15).default(5), room: z.string().optional() }) }, async ({ characterId, ...rest }) => output(await hub("/api/recall", { method: "POST", body: { charId: characterId, ...rest } })));
  server.registerTool("sully_get_runtime_state", { description: "Get the authoritative character snapshot and runtime state.", inputSchema: z.object({ characterId: z.string().min(1) }) }, async ({ characterId }) => output(await hub(`/api/v1/characters/${encodeURIComponent(characterId)}/snapshot`)));
  server.registerTool("sully_commit_activity", { description: "Commit a CC free activity verbatim, optional user-visible message, and optional state patch atomically. Completes the claimed wake when wakeRunId and leaseToken are supplied.", inputSchema: z.object({ characterId: z.string().min(1), activityId: z.string().min(1), content: z.string().min(1), occurredAt: z.string().optional(), visibility: z.enum(["internal", "user"]).default("internal"), statePatch: z.record(z.string(), z.unknown()).optional(), userMessage: z.object({ messageId: z.string().min(1), content: z.string().min(1), role: z.string().default("assistant"), occurredAt: z.string().optional() }).optional(), wakeRunId: z.string().optional(), leaseToken: z.string().optional(), sessionId: z.string().optional(), deliveryTargets: z.array(z.string()).optional(), commandId: z.string().optional() }) }, async (args) => output(await hub("/api/v1/runtime/commands", { method: "POST", body: command("runtime.activity.commit", args.characterId, { activity: { activityId: args.activityId, content: args.content, occurredAt: args.occurredAt, visibility: args.visibility }, statePatch: args.statePatch || {}, userMessage: args.userMessage, wakeRunId: args.wakeRunId, leaseToken: args.leaseToken, sessionId: args.sessionId, deliveryTargets: args.deliveryTargets || [] }, args.commandId) })));
  server.registerTool("sully_commit_message", { description: "Commit one stable-ID CC message directly to Hub without passing it through another model.", inputSchema: z.object({ characterId: z.string().min(1), messageId: z.string().min(1), content: z.string().min(1), role: z.string().default("assistant"), surface: z.enum(["chat", "activity", "world", "state", "memory", "schedule", "system"]).default("chat"), visibility: z.enum(["user", "internal"]).default("user"), occurredAt: z.string().optional(), deliveryTargets: z.array(z.string()).optional(), commandId: z.string().optional() }) }, async ({ deliveryTargets, commandId, ...message }) => output(await hub("/api/v1/runtime/commands", { method: "POST", body: command("runtime.message.commit", message.characterId, { message, deliveryTargets: deliveryTargets || [] }, commandId) })));
  server.registerTool("sully_schedule_wake", { description: "Schedule a future CC autonomy wake in the Hub scheduler.", inputSchema: z.object({ characterId: z.string().min(1), jobId: z.string().min(1), dueAt: z.string(), reason: z.string().min(1), jobType: z.enum(["brain.wake", "autonomy.wake", "computer.task"]).default("autonomy.wake"), deliveryTargets: z.array(z.string()).optional(), commandId: z.string().optional() }) }, async (args) => output(await hub("/api/v1/runtime/commands", { method: "POST", body: command("schedule.job.put", args.characterId, { job: { jobId: args.jobId, jobType: args.jobType, dueAt: args.dueAt, payload: { reason: args.reason, deliveryTargets: args.deliveryTargets || [] } } }, args.commandId) })));
  server.registerTool("sully_cancel_wake", { description: "Cancel a queued Hub wake by stable job ID.", inputSchema: z.object({ characterId: z.string().min(1), jobId: z.string().min(1), commandId: z.string().optional() }) }, async (args) => output(await hub("/api/v1/runtime/commands", { method: "POST", body: command("schedule.job.cancel", args.characterId, { jobId: args.jobId }, args.commandId) })));
  server.registerTool("sully_list_events", { description: "List incremental Hub events for one character.", inputSchema: z.object({ characterId: z.string().min(1), after: z.number().int().min(0).default(0), limit: z.number().int().min(1).max(500).default(100) }) }, async ({ characterId, after, limit }) => output(await hub(`/v1/events?characterId=${encodeURIComponent(characterId)}&after=${after}&limit=${limit}`)));
  return server;
}

void serveStdio(createServer);
console.error(`Sully Memory Hub MCP ready for ${baseUrl}`);
